plugins {
    id 'java'
    id 'maven-publish'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
    withJavadocJar()
}

// Quiet warnings about missing Javadocs.
javadoc {
    options.addStringOption('Xdoclint:-missing', '-quiet')
}

// Adds the Hytale server as a build dependency, allowing you to reference and
dependencies {
    compileOnly("com.hypixel.hytale:Server:$hytale_build")
}

repositories {
    mavenCentral()
    google()
    maven {
        name = "hytale-release"
        url = uri("https://maven.hytale.com/release")
    }
    maven {
        name = "hytale-pre-release"
        url = uri("https://maven.hytale.com/pre-release")
    }
}
base {
    archivesName = "CodecAnnotation"
}
tasks.named('jar') {
    archiveFileName.set("CodecAnnotation-${version}.jar")
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java

            groupId = "com.github.rm20killer"
            artifactId = "codecannotation"
            version = "${version}"
        }
    }
}